const auth = {
    AUTHENTICATE: 'AUTHENTICATE',
    DEAUTHENTICATE: 'DEAUTHENTICATE',
    RESTORE_AUTH_STATE: 'RESTORE_AUTH_STATE',
    AUTHENTICATE_VK: 'AUTHENTICATE_VK',
    AUTHENTICATE_GOOGLE: 'AUTHENTICATE_GOOGLE',
    AUTHENTICATE_TELEGRAM: 'AUTHENTICATE_TELEGRAM',
    AUTHENTICATE_FACEBOOK: 'AUTHENTICATE_FACEBOOK',
}
export default auth