import type { NextPage } from 'next'
import Head from 'next/head'

import { Description } from '../components/Description'
import { Steps } from '../components/Steps'
import { Causes } from '../components/Сauses'
import { Footer } from '../components/Footer'
import { TextContainer } from '../components/TextContainer'
import { Banner } from '../components/Banner'
import { Navbar } from '../components/Navbars/Navbar'

import card from '../public/icons/card.svg';
import grave from '../public/icons/grave.svg';
import page from '../public/icons/page.svg';
import qrcode from '../public/icons/qr-code.svg';


const steps = [
  {icon: page, text: "Зарегистрироваться и создать страницу"},
  {icon: card, text: "Оплатить страницу"},
  {icon: qrcode, text: "Получите QR-код"},
  {icon: grave, text: "Добавьте его на могилу"}
]



import logoStar from '../public/icons/logo_star.svg'
import logoAd from '../public/icons/logo_ad.svg'
import logoClock from '../public/icons/logo_clock.svg'
import logoConf from '../public/icons/logo_conf.svg'
import logoSave from '../public/icons/logo_save.svg'
import logoEdit from '../public/icons/logo_edit.svg'
import logoScan from '../public/icons/logo_scan.svg'
import logoSettings from '../public/icons/logo_setting.svg'



const causes = [
  {icon: logoScan, title: "QR- код считываются с любого устройства", text: "Достаточно открыть камеру и навести объектив мобильного устройства на QR-код и получить быстрый доступ к информации"},
  {icon: logoSave, title: "Резервное копирование данных", text: "Резервное копирование защищает вас от любого вида потери данных при сбое, краже, взломе вашего аккаунта"},
  {icon: logoAd, title: "Отсутствие рекламы", text: "Надоела назойливая реклама? На нашем сайте вы ее никогда не увидите"},
  {icon: logoConf, title: "Конфиденциальность информации", text: "Мы берём на себя полную ответственность за сохранность любой вашей информации"},
  {icon: logoSettings, title: "Пожизненное тех. обслуживание страниц", text: "Любая оплаченная страница будет работать и сегодня, и завтра, и через 5 лет"},
  {icon: logoStar, title: "Инновационная услуга", text: "Хотите окунуться в будущее? Вы это можете сделать уже сейчас, воспользовавшись нашей новаторской услугой"},
  {icon: logoEdit, title: "Возможность редактировать и удалять страницу", text: "Поскольку мы все иногда совершаем ошибки, созданные страницы можно редактировать и удалять"},
  {icon: logoClock, title: "Бесплатный пробный период 3 дня", text: "Это бесплатный период использования нашей услуги для пользователей, в течение которого можно оценить сервис и понять, насколько он вам подходит"},
]


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ritual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>
        <Banner/>
        <Description/>
        <Steps steps={steps}/>
        <Causes causes={causes}/>
        <TextContainer/>
      </main>
      <Footer/>
    </div>
  )
}

export default Home
