# Generated by Django 3.2.8 on 2021-12-27 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='qr_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=[], size=None),
        ),
    ]
