# Generated by Django 3.2.8 on 2021-12-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_pages_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=100)),
                ('activation_date', models.DateField(null=True, verbose_name='Дата создания')),
            ],
        ),
    ]
