# Generated by Django 3.2.8 on 2022-01-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_promocode_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='last_time_opened',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
