# Generated by Django 3.2.8 on 2021-11-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
