# Generated by Django 3.2.8 on 2021-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211124_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_google',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_vk',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
