# Generated by Django 3.2.8 on 2021-12-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20211215_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
