# Generated by Django 3.2.8 on 2022-01-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_delete_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_new_things',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_promotion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_suspicious',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_unidentified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_useful_information',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='remind_after',
            field=models.IntegerField(default=3),
        ),
    ]
